/*
1.3.31　实现一个嵌套类 DoubleNode 用来构造双向链表，其中每个结点都含有一个指向前驱元素的引用和一项指向后续元素的引用（如果不存在则为 null）。为以下任务实现若干静态方法：在表头插入结点、在表尾插入结点、从表头删除结点、从表尾删除结点、在指定结点之前插入新结点、在指定结点之后插入新结点、删除指定结点。
 */

import { DoubleLinkedList } from '../DoubleLinkedList'

describe('1.3.31', () => {
  it('测试链表尾部操作', () => {
    const list = new DoubleLinkedList()
    list.push(1)
    list.push(2)
    list.push(3)
    expect(list.pop()).toBe(3)
    expect(list.pop()).toBe(2)
    expect(list.pop()).toBe(1)
    expect(list.pop()).toBeNull()
    expect(list.isEmpty).toBeTruthy()
  })
  it('测试链表头部操作', () => {
    const list = new DoubleLinkedList()
    list.unshift(1)
    list.unshift(2)
    list.unshift(3)
    expect(list.shift()).toBe(3)
    expect(list.shift()).toBe(2)
    expect(list.shift()).toBe(1)
    expect(list.shift()).toBeNull()
    expect(list.isEmpty).toBeTruthy()
  })
  it('测试链表两侧混合操作', () => {
    const list = new DoubleLinkedList()
    list.push(1)
    list.push(2)
    list.push(3)
    expect(list.shift()).toBe(1)
    expect(list.shift()).toBe(2)
    expect(list.shift()).toBe(3)
    expect(list.isEmpty).toBeTruthy()
  })
  it('测试 get', () => {
    const list = new DoubleLinkedList()
    list.push(1)
    expect(list.get(0)).toBe(1)
    expect(list.get(3)).toBeNull()
  })
  it('测试 insertBefore', () => {
    const list = new DoubleLinkedList<number>()
    list.insertBefore(10, 1)
    expect(list.isEmpty).toBeTruthy()
    list.push(1)
    list.push(2)
    list.insertBefore(0, 0)
    expect(list.size).toBe(3)
    expect(list.shift()).toBe(0)
    list.insertBefore(1, 3)
    expect([...list]).toStrictEqual([1, 3, 2])
  })
  it('测试 insertAfter', () => {
    const list = new DoubleLinkedList<number>()
    list.insertAfter(10, 1)
    expect(list.isEmpty).toBeTruthy()
    list.push(1)
    list.push(2)
    list.insertAfter(1, 3)
    expect(list.size).toBe(3)
    expect(list.pop()).toBe(3)
    console.log([...list])
    list.insertAfter(0, 3)
    expect([...list]).toStrictEqual([1, 3, 2])
  })
  it('测试 remove', () => {
    const list = new DoubleLinkedList<number>()
    list.push(1)
    list.push(2)
    list.push(3)
    expect(list.remove(1)).toBe(2)
    expect(list.remove(1)).toBe(3)
    expect(list.remove(1)).toBeNull()
    expect(list.remove(0)).toBe(1)
    expect(list.isEmpty).toBeTruthy()
  })
})
